from django.db import models

# Create your models here.

STATUS = (
    ("Active", "Active"),
    ("Inactive", "Inactive"),
    ("Delete", "Delete")
)

class SliderTabs(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with Tab")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with Tab")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Tab")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Tab")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    tabKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the tab")
    tabLabel = models.CharField(max_length=45,null=False,blank=False,help_text="label for the tab")
    tabIcon = models.CharField(max_length=255,null=True,blank=True,help_text="icon for the tab")
    tabPermission = models.BooleanField(null=False,blank=False,default=True,help_text="permission for the tab")
    # parentId = models.IntegerField(null=True,blank=True,help_text="This filed used when we create sub actions under the main action,it takes parent action Id")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="Tab status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)

class LayoutElements(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with KPI")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with KPI")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Action")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Action")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    layoutElementKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the KPI")
    layoutElementName = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Title for the KPI")
    parentId = models.IntegerField(null=True,blank=True,default=0,help_text="parent Id asscoaited with slider Tabs")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="kpi status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)

class KPICards(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with KPI")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with KPI")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Action")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Action")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    kpiCardKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the KPI")
    kpiCardTitle = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Title for the KPI")
    parentId = models.IntegerField(null=True,blank=True,default=0,help_text="parent Id asscoaited with slider Tabs")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="kpi status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)

class HighlightKPIs(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with KPI")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with KPI")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Action")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Action")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    highlightKpiKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the KPI")
    highlightKpiTitle = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Title for the KPI")
    parentId = models.IntegerField(null=True,blank=True,default=0,help_text="parent Id asscoaited with slider Tabs")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="kpi status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)

class AlertKPIs(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with KPI")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with KPI")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Action")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Action")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    alertKpiKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the KPI")
    alertKpiTitle = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Title for the KPI")
    parentId = models.IntegerField(null=True,blank=True,default=0,help_text="parent Id asscoaited with slider Tabs")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="kpi status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)

class QuickConnects(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with KPI")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with KPI")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Action")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Action")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    quickConnectKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the KPI")
    quickConnectTitle = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Title for the KPI")
    parentId = models.IntegerField(null=True,blank=True,default=0,help_text="parent Id asscoaited with slider Tabs")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="kpi status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)

class KPIFilters(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with KPI")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with KPI")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Action")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Action")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    kpiFilterKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the KPI")
    kpiFilterTitle = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Title for the KPI")
    parentId = models.IntegerField(null=True,blank=True,default=0,help_text="parent Id asscoaited with slider Tabs")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="kpi status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)

class KPICharts(models.Model):
    id = models.AutoField(primary_key=True)
    fkCompanyId = models.IntegerField(null=False,blank=False,help_text="Company associated with KPI")
    fkProjectId = models.IntegerField(null=False,blank=False,help_text="Project associated with KPI")
    # fkPhaseId = models.IntegerField(null=True,blank=True,help_text="Phase associated with Action")
    # fkUnitId = models.IntegerField(null=True,blank=True,help_text="Unit associated with Action")
    fkProjectStructureIds = models.CharField(max_length=255,null=False,blank=False,default="Not Mentioned",help_text="Values will separated by : (1L12:2L232:3L44)")
    kpiKey = models.CharField(max_length=45,unique=True,null=False,blank=False,help_text="unique key for the KPI")
    kpiChartTitle = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Title for the KPI")
    kpiChartType = models.CharField(max_length=45,null=False,blank=False,help_text="Chart Type for the KPI")
    kpiContext = models.CharField(max_length=45,null=False,blank=False,help_text="context for the KPI")
    kpiModule = models.CharField(max_length=45,null=False,blank=False,help_text="module for the KPI")
    kpiAnalytics = models.CharField(max_length=255,null=False,blank=False,help_text="module for the KPI")
    kpiAnalyticsDetails = models.CharField(max_length=255,null=False,blank=False,help_text="module for the KPI")
    kpiChartOptions = models.TextField(null=True,help_text="module for the KPI")
    kpiChartSize =  models.CharField(max_length=45,null=True,help_text="module for the KPI")
    page = models.IntegerField(null=True,help_text="Project associated with KPI")
    kpiPosition =  models.IntegerField(null=True,help_text="Project associated with KPI")
    kpiChartComponent =  models.TextField(null=True,help_text="module for the KPI")
    parentId = models.IntegerField(null=True,blank=True,default=0,help_text="parent Id asscoaited with slider Tabs")
    status = models.CharField(max_length=45,choices=STATUS,default="Active",null=False,blank=False,help_text="kpi status")
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    createdBy = models.IntegerField(blank=False, null=False)
    updatedBy = models.IntegerField(blank=True, null=True)